/**
 * Demo account seeder for Aftertaste
 * Run with: node scripts/seedDemoAccount.mjs
 *
 * Requires SUPABASE_SERVICE_ROLE_KEY in your .env
 * (service role key, NOT anon key — needed to create auth users)
 */

import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: join(__dirname, '../.env') });

const SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL;
const SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SERVICE_ROLE_KEY) {
  console.error('❌  Missing env vars. Add SUPABASE_SERVICE_ROLE_KEY to your .env file.');
  console.error('    Find it at: Supabase Dashboard → Settings → API → service_role key');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

const DEMO_EMAIL = 'demo@gmail.com';
const DEMO_PASSWORD = 'demo';

function computeComposite(taste, vibe, value) {
  return Math.round((taste * 0.5 + vibe * 0.25 + value * 0.25) * 10) / 10;
}

const MEMORIES = [
  {
    restaurant_name: "Carbone",
    price_tier: '$$$',
    eatery_type: 'Fine Dining',
    cuisine_type: 'Italian Restaurant',
    address: '181 Thompson St, New York, NY',
    city: 'New York City',
    state: 'NY',
    latitude: 40.7279,
    longitude: -74.0002,
    date: '2025-11-14',
    photos: ['https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600'],
    what_i_had: ['Spicy Rigatoni Vodka', 'Veal Parmesan', 'Tiramisu'],
    occasion_tag: 'Date Night',
    mood_tag: 'Perfect',
    taste_rating: 'Great',
    vibe_rating: 'Great',
    value_rating: 'Okay',
    taste_score: 9.5,
    vibe_score: 9.5,
    value_score: 5.5,
    composite_score: computeComposite(9.5, 9.5, 5.5),
    eat_again: true,
    squad: [{ id: 's1', name: 'Sofia', avatar: 'https://i.pravatar.cc/100?img=5' }],
    memory_note: 'Spicy rigatoni lives up to every bit of the hype. The vibe is old-school NYC glamour — suits, dim lighting, Sinatra playing. Worth every penny for a special night.',
    is_favorite: true,
    visits: [],
    photo_dates: {},
  },
  {
    restaurant_name: "Nobu Malibu",
    price_tier: '$$$$',
    eatery_type: 'Restaurant',
    cuisine_type: 'Japanese Restaurant',
    address: '22706 Pacific Coast Hwy, Malibu, CA',
    city: 'Malibu',
    state: 'CA',
    latitude: 34.0375,
    longitude: -118.6919,
    date: '2025-10-02',
    photos: ['https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600'],
    what_i_had: ['Black Cod Miso', 'Rock Shrimp Tempura', 'Yellowtail Jalapeño'],
    occasion_tag: 'Celebration',
    mood_tag: 'Perfect',
    taste_rating: 'Great',
    vibe_rating: 'Great',
    value_rating: 'Okay',
    taste_score: 9.8,
    vibe_score: 9.2,
    value_score: 5.0,
    composite_score: computeComposite(9.8, 9.2, 5.0),
    eat_again: true,
    squad: [
      { id: 's2', name: 'Marcus', avatar: 'https://i.pravatar.cc/100?img=12' },
      { id: 's3', name: 'Priya', avatar: 'https://i.pravatar.cc/100?img=9' },
    ],
    memory_note: 'The black cod miso is transcendent. Sat outside watching the sunset over the Pacific. One of those meals you remember forever.',
    is_favorite: true,
    visits: [],
    photo_dates: {},
  },
  {
    restaurant_name: "Franklin Barbecue",
    price_tier: '$$',
    eatery_type: 'Restaurant',
    cuisine_type: 'BBQ Restaurant',
    address: '900 E 11th St, Austin, TX',
    city: 'Austin',
    state: 'TX',
    latitude: 30.2669,
    longitude: -97.7289,
    date: '2025-09-20',
    photos: ['https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=600'],
    what_i_had: ['Brisket', 'Pork Ribs', 'Sausage', 'Banana Pudding'],
    occasion_tag: 'Everyday Meal',
    mood_tag: 'Adventurous',
    taste_rating: 'Great',
    vibe_rating: 'Okay',
    value_rating: 'Great',
    taste_score: 10.0,
    vibe_score: 7.0,
    value_score: 8.5,
    composite_score: computeComposite(10.0, 7.0, 8.5),
    eat_again: true,
    squad: [{ id: 's4', name: 'Jake', avatar: 'https://i.pravatar.cc/100?img=11' }],
    memory_note: "Waited 3 hours in line. Zero regrets. The brisket melts in your mouth in a way that makes you understand why people fly to Austin just for this. 10/10 no notes.",
    is_favorite: true,
    visits: [],
    photo_dates: {},
  },
  {
    restaurant_name: "République",
    price_tier: '$$$',
    eatery_type: 'Cafe',
    cuisine_type: 'French Cafe',
    address: '624 S La Brea Ave, Los Angeles, CA',
    city: 'Los Angeles',
    state: 'CA',
    latitude: 34.0612,
    longitude: -118.3446,
    date: '2025-12-08',
    photos: ['https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600'],
    what_i_had: ['Croissant', 'Croque Madame', 'Lavender Latte'],
    occasion_tag: 'Everyday Meal',
    mood_tag: 'Calm',
    taste_rating: 'Great',
    vibe_rating: 'Great',
    value_rating: 'Okay',
    taste_score: 9.0,
    vibe_score: 9.0,
    value_score: 6.0,
    composite_score: computeComposite(9.0, 9.0, 6.0),
    eat_again: true,
    squad: [],
    memory_note: 'Sunday morning solo brunch. The space is stunning — vaulted ceilings, natural light everywhere. Best croissant in LA, and that lavender latte was a 10.',
    is_favorite: true,
    visits: [
      {
        id: 'v-rep-1',
        date: '2026-01-12',
        whatIHad: ['Almond Croissant', 'Cappuccino'],
        note: 'Came back just for the croissants. Still perfect.',
        tasteRating: 'Great',
        vibeRating: 'Great',
        valueRating: 'Okay',
        tasteScore: 9.0,
        vibeScore: 9.0,
        valueScore: 6.0,
        compositeScore: computeComposite(9.0, 9.0, 6.0),
      },
    ],
    photo_dates: {},
  },
  {
    restaurant_name: "Katsu-ya",
    price_tier: '$$',
    eatery_type: 'Restaurant',
    cuisine_type: 'Japanese Restaurant',
    address: '11680 Ventura Blvd, Studio City, CA',
    city: 'Studio City',
    state: 'CA',
    latitude: 34.1386,
    longitude: -118.3936,
    date: '2025-08-15',
    photos: ['https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=600'],
    what_i_had: ['Crispy Rice with Spicy Tuna', 'Baked Crab Roll', 'Albacore Sashimi'],
    occasion_tag: 'Everyday Meal',
    mood_tag: 'Craving',
    taste_rating: 'Great',
    vibe_rating: 'Okay',
    value_rating: 'Great',
    taste_score: 9.2,
    vibe_score: 7.5,
    value_score: 8.0,
    composite_score: computeComposite(9.2, 7.5, 8.0),
    eat_again: true,
    squad: [{ id: 's5', name: 'Lena', avatar: 'https://i.pravatar.cc/100?img=7' }],
    memory_note: "The crispy rice is genuinely addictive. We ordered two. No regrets. This is LA comfort sushi at its best — not pretentious, just really really good.",
    is_favorite: false,
    visits: [],
    photo_dates: {},
  },
  {
    restaurant_name: "Alinea",
    price_tier: '$$$$',
    eatery_type: 'Fine Dining',
    cuisine_type: 'Fine Dining',
    address: '1723 N Halsted St, Chicago, IL',
    city: 'Chicago',
    state: 'IL',
    latitude: 41.9138,
    longitude: -87.6486,
    date: '2025-07-04',
    photos: ['https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600'],
    what_i_had: ['18-Course Tasting Menu', 'Wine Pairing'],
    occasion_tag: 'Celebration',
    mood_tag: 'Adventurous',
    taste_rating: 'Great',
    vibe_rating: 'Great',
    value_rating: 'Okay',
    taste_score: 9.7,
    vibe_score: 9.8,
    value_score: 5.0,
    composite_score: computeComposite(9.7, 9.8, 5.0),
    eat_again: true,
    squad: [{ id: 's1', name: 'Sofia', avatar: 'https://i.pravatar.cc/100?img=5' }],
    memory_note: 'A 3-hour art experience disguised as dinner. The edible balloon dessert alone is worth the trip to Chicago. Bucket list meal, absolutely checked off.',
    is_favorite: true,
    visits: [],
    photo_dates: {},
  },
  {
    restaurant_name: "Shake Shack",
    price_tier: '$',
    eatery_type: 'Fast Casual',
    cuisine_type: 'Burger Joint',
    address: 'Madison Square Park, New York, NY',
    city: 'New York City',
    state: 'NY',
    latitude: 40.7418,
    longitude: -73.9881,
    date: '2026-01-28',
    photos: ['https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600'],
    what_i_had: ['ShackBurger', 'Cheese Fries', 'Concrete'],
    occasion_tag: 'Everyday Meal',
    mood_tag: 'Comforting',
    taste_rating: 'Great',
    vibe_rating: 'Okay',
    value_rating: 'Okay',
    taste_score: 8.0,
    vibe_score: 7.0,
    value_score: 6.5,
    composite_score: computeComposite(8.0, 7.0, 6.5),
    eat_again: true,
    squad: [],
    memory_note: "Classic NYC lunch. The original Madison Square Park location still hits different. Long line but moved fast. Cheese fries are dangerously good.",
    is_favorite: false,
    visits: [],
    photo_dates: {},
  },
  {
    restaurant_name: "Erewhon Market",
    price_tier: '$$$',
    eatery_type: 'Cafe',
    cuisine_type: 'Health Food',
    address: '7660 Beverly Blvd, Los Angeles, CA',
    city: 'Los Angeles',
    state: 'CA',
    latitude: 34.0746,
    longitude: -118.3611,
    date: '2026-02-10',
    photos: ['https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600'],
    what_i_had: ['Hailey Bieber Smoothie', 'Acai Bowl', 'Avocado Toast'],
    occasion_tag: 'Everyday Meal',
    mood_tag: 'Adventurous',
    taste_rating: 'Great',
    vibe_rating: 'Great',
    value_rating: 'Poor',
    taste_score: 8.5,
    vibe_score: 8.0,
    value_score: 3.0,
    composite_score: computeComposite(8.5, 8.0, 3.0),
    eat_again: true,
    squad: [{ id: 's3', name: 'Priya', avatar: 'https://i.pravatar.cc/100?img=9' }],
    memory_note: "$25 for a smoothie. Was it life-changing? Kind of yes. The people watching alone is worth it. Peak LA experience. I'm going back.",
    is_favorite: false,
    visits: [],
    photo_dates: {},
  },
  {
    restaurant_name: "Momofuku Noodle Bar",
    price_tier: '$$',
    eatery_type: 'Restaurant',
    cuisine_type: 'Ramen Restaurant',
    address: '171 1st Ave, New York, NY',
    city: 'New York City',
    state: 'NY',
    latitude: 40.7269,
    longitude: -73.9818,
    date: '2025-12-30',
    photos: ['https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=600'],
    what_i_had: ['Pork Belly Buns', 'Spicy Miso Ramen', 'Soft Serve'],
    occasion_tag: 'Everyday Meal',
    mood_tag: 'Comforting',
    taste_rating: 'Great',
    vibe_rating: 'Okay',
    value_rating: 'Okay',
    taste_score: 9.0,
    vibe_score: 7.0,
    value_score: 7.0,
    composite_score: computeComposite(9.0, 7.0, 7.0),
    eat_again: true,
    squad: [{ id: 's4', name: 'Jake', avatar: 'https://i.pravatar.cc/100?img=11' }],
    memory_note: 'Cold winter night, bowl of ramen, best pork buns in the city. The soft serve at the end was an unexpected highlight. Classic downtown NYC energy.',
    is_favorite: false,
    visits: [],
    photo_dates: {},
  },
  {
    restaurant_name: "Bottega Louie",
    price_tier: '$$',
    eatery_type: 'Restaurant',
    cuisine_type: 'Italian Restaurant',
    address: '700 S Grand Ave, Los Angeles, CA',
    city: 'Los Angeles',
    state: 'CA',
    latitude: 34.0472,
    longitude: -118.2573,
    date: '2026-03-01',
    photos: ['https://images.unsplash.com/photo-1551183053-bf91798d792e?w=600'],
    what_i_had: ['Burrata', 'Tagliatelle Bolognese', 'Macarons'],
    occasion_tag: 'Date Night',
    mood_tag: 'Nostalgic',
    taste_rating: 'Great',
    vibe_rating: 'Great',
    value_rating: 'Okay',
    taste_score: 8.5,
    vibe_score: 9.0,
    value_score: 6.5,
    composite_score: computeComposite(8.5, 9.0, 6.5),
    eat_again: true,
    squad: [{ id: 's1', name: 'Sofia', avatar: 'https://i.pravatar.cc/100?img=5' }],
    memory_note: 'Stunning space — all marble and white. The macarons in the pastry case are almost too pretty to eat. Almost. Great for a date, not for a tight budget.',
    is_favorite: false,
    visits: [],
    photo_dates: {},
  },
  {
    restaurant_name: "Bad Roman",
    price_tier: '$$$',
    eatery_type: 'Restaurant',
    cuisine_type: 'Italian Restaurant',
    address: '1 Columbus Circle, New York, NY',
    city: 'New York City',
    state: 'NY',
    latitude: 40.7683,
    longitude: -73.9820,
    date: '2025-11-01',
    photos: ['https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=600'],
    what_i_had: ['Grandma Slice Pasta', 'Wagyu Bolognese', 'Olive Oil Cake'],
    occasion_tag: 'Celebration',
    mood_tag: 'Perfect',
    taste_rating: 'Great',
    vibe_rating: 'Great',
    value_rating: 'Okay',
    taste_score: 9.3,
    vibe_score: 9.5,
    value_score: 6.0,
    composite_score: computeComposite(9.3, 9.5, 6.0),
    eat_again: true,
    squad: [
      { id: 's2', name: 'Marcus', avatar: 'https://i.pravatar.cc/100?img=12' },
      { id: 's5', name: 'Lena', avatar: 'https://i.pravatar.cc/100?img=7' },
    ],
    memory_note: 'The grandma slice pasta is one of the most creative dishes I have had in years. Loud, fun, beautiful crowd. This is what going out in NYC should feel like.',
    is_favorite: true,
    visits: [],
    photo_dates: {},
  },
  {
    restaurant_name: "Tartine Bakery",
    price_tier: '$',
    eatery_type: 'Bakery',
    cuisine_type: 'Bakery',
    address: '600 Guerrero St, San Francisco, CA',
    city: 'San Francisco',
    state: 'CA',
    latitude: 37.7614,
    longitude: -122.4241,
    date: '2025-06-15',
    photos: ['https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=600'],
    what_i_had: ['Country Loaf', 'Morning Bun', 'Croque Monsieur'],
    occasion_tag: 'Everyday Meal',
    mood_tag: 'Adventurous',
    taste_rating: 'Great',
    vibe_rating: 'Okay',
    value_rating: 'Great',
    taste_score: 9.5,
    vibe_score: 7.5,
    value_score: 8.5,
    composite_score: computeComposite(9.5, 7.5, 8.5),
    eat_again: true,
    squad: [],
    memory_note: "Took the BART to the Mission just for this. The country loaf is the best bread I've ever had — and I've had a lot of bread. The morning bun is criminally good.",
    is_favorite: true,
    visits: [],
    photo_dates: {},
  },
  {
    restaurant_name: "Catch LA",
    price_tier: '$$$',
    eatery_type: 'Restaurant',
    cuisine_type: 'Seafood Restaurant',
    address: '8715 Melrose Ave, West Hollywood, CA',
    city: 'West Hollywood',
    state: 'CA',
    latitude: 34.0828,
    longitude: -118.3777,
    date: '2026-02-22',
    photos: ['https://images.unsplash.com/photo-1560717845-968823efbee1?w=600'],
    what_i_had: ['Lobster Tacos', 'Yellowfin Tuna Tartare', 'Miso Glazed Sea Bass'],
    occasion_tag: 'Celebration',
    mood_tag: 'Perfect',
    taste_rating: 'Great',
    vibe_rating: 'Great',
    value_rating: 'Poor',
    taste_score: 8.8,
    vibe_score: 9.2,
    value_score: 4.5,
    composite_score: computeComposite(8.8, 9.2, 4.5),
    eat_again: true,
    squad: [
      { id: 's1', name: 'Sofia', avatar: 'https://i.pravatar.cc/100?img=5' },
      { id: 's3', name: 'Priya', avatar: 'https://i.pravatar.cc/100?img=9' },
      { id: 's5', name: 'Lena', avatar: 'https://i.pravatar.cc/100?img=7' },
    ],
    memory_note: 'The rooftop views are unbeatable. Lobster tacos alone are worth the trip. Expensive but this is the WeHo experience. Sunset hour is magical up there.',
    is_favorite: false,
    visits: [],
    photo_dates: {},
  },
  {
    restaurant_name: "Russ & Daughters",
    price_tier: '$$',
    eatery_type: 'Cafe',
    cuisine_type: 'Cafe',
    address: '127 Orchard St, New York, NY',
    city: 'New York City',
    state: 'NY',
    latitude: 40.7218,
    longitude: -73.9895,
    date: '2025-05-10',
    photos: ['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600'],
    what_i_had: ['Classic Bagel & Lox', 'Borscht', 'Babka'],
    occasion_tag: 'Everyday Meal',
    mood_tag: 'Nostalgic',
    taste_rating: 'Great',
    vibe_rating: 'Great',
    value_rating: 'Okay',
    taste_score: 9.5,
    vibe_score: 9.3,
    value_score: 6.5,
    composite_score: computeComposite(9.5, 9.3, 6.5),
    eat_again: true,
    squad: [{ id: 's4', name: 'Jake', avatar: 'https://i.pravatar.cc/100?img=11' }],
    memory_note: 'A century-old New York institution. The lox is impeccable, the babka sinful. Walking into this place feels like stepping back in time. A must-do in the Lower East Side.',
    is_favorite: true,
    visits: [],
    photo_dates: {},
  },
  {
    restaurant_name: "Souvla",
    price_tier: '$',
    eatery_type: 'Fast Casual',
    cuisine_type: 'Greek Restaurant',
    address: '517 Hayes St, San Francisco, CA',
    city: 'San Francisco',
    state: 'CA',
    latitude: 37.7763,
    longitude: -122.4236,
    date: '2025-06-16',
    photos: ['https://images.unsplash.com/photo-1544025162-d76538b2pde3?w=600&fit=crop'],
    what_i_had: ['Lamb Wrap', 'Frozen Greek Yogurt', 'Lemon Potatoes'],
    occasion_tag: 'Everyday Meal',
    mood_tag: 'Perfect',
    taste_rating: 'Great',
    vibe_rating: 'Great',
    value_rating: 'Great',
    taste_score: 9.2,
    vibe_score: 8.5,
    value_score: 9.0,
    composite_score: computeComposite(9.2, 8.5, 9.0),
    eat_again: true,
    squad: [],
    memory_note: "Fast-casual Greek done perfectly. The lamb wrap is one of the best things I've eaten this year. And the frozen Greek yogurt? Life-changing. SF hidden gem.",
    is_favorite: true,
    visits: [],
    photo_dates: {},
  },
];

async function main() {
  console.log('🌱  Seeding demo account for Aftertaste...\n');

  // 1. Check if demo user already exists
  const { data: existingUsers } = await supabase.auth.admin.listUsers();
  const existing = existingUsers?.users?.find(u => u.email === DEMO_EMAIL);

  let userId;

  if (existing) {
    console.log(`⚠️  Demo account already exists (${DEMO_EMAIL}) — using existing user.`);
    userId = existing.id;

    // Clear existing memories for a fresh seed
    const { error: deleteError } = await supabase
      .from('memories')
      .delete()
      .eq('user_id', userId);
    if (deleteError) console.warn('  Could not clear old memories:', deleteError.message);
    else console.log('  ✓ Cleared old memories');
  } else {
    // 2. Create demo user
    const { data: newUser, error: createError } = await supabase.auth.admin.createUser({
      email: DEMO_EMAIL,
      password: DEMO_PASSWORD,
      email_confirm: true,
    });

    if (createError || !newUser?.user) {
      console.error('❌  Failed to create demo user:', createError?.message);
      process.exit(1);
    }

    userId = newUser.user.id;
    console.log(`✓  Created demo user: ${DEMO_EMAIL} / ${DEMO_PASSWORD}`);
  }

  // 3. Insert memories
  const rows = MEMORIES.map(m => ({ ...m, user_id: userId }));
  const { error: insertError } = await supabase.from('memories').insert(rows);

  if (insertError) {
    console.error('❌  Failed to insert memories:', insertError.message);
    process.exit(1);
  }

  console.log(`✓  Inserted ${MEMORIES.length} memories\n`);
  console.log('🎉  Done! Demo account ready:');
  console.log(`    Email:    ${DEMO_EMAIL}`);
  console.log(`    Password: ${DEMO_PASSWORD}`);
}

main().catch(console.error);
